# Generated by Django 5.0.6 on 2024-05-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_options_user_first_name_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fam',
        ),
    ]
