# Generated by Django 5.0.6 on 2024-05-31 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='DishHalf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('calories', models.FloatField(max_length=10, verbose_name='Калории')),
                ('proteins', models.FloatField(max_length=10, verbose_name='Протеины')),
                ('fats', models.FloatField(max_length=10, verbose_name='Жиры')),
                ('carbs', models.FloatField(max_length=10, verbose_name='Углеводы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_halves', to='health_app.category', verbose_name='Категория')),
                ('contraindications', models.ManyToManyField(blank=True, to='health_app.allergy', verbose_name='Противопоказания')),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half1', to='health_app.dishhalf', verbose_name='Первая половина')),
                ('half2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half2', to='health_app.dishhalf', verbose_name='Вторая половина')),
            ],
            options={
                'unique_together': {('half1', 'half2')},
            },
        ),
    ]
