# Generated by Django 5.0.6 on 2024-05-29 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('fam', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('phone', models.TextField(max_length=15, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('weight', models.FloatField(max_length=3, verbose_name='Вес')),
                ('height', models.FloatField(max_length=3, verbose_name='Рост')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Список аллергенов')),
                ('activity_level', models.FloatField(choices=[(1.2, 'Минимальная активность, сидячая работа'), (1.375, 'Слабый уровень активности'), (1.55, 'Умеренный уровень активности'), (1.7, 'Тяжелая или трудоемкая активность'), (1.9, 'Экстремальный уровень активности')], default=1.2, verbose_name='Уровень активности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishHalf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField(max_length=10, verbose_name='Калории')),
                ('proteins', models.FloatField(max_length=10, verbose_name='Протеины')),
                ('fats', models.FloatField(max_length=10, verbose_name='Жиры')),
                ('carbs', models.FloatField(max_length=10, verbose_name='Углеводы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_halves', to='health_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dish_halves', models.ManyToManyField(to='health_app.dishhalf')),
            ],
        ),
    ]
