# Generated by Django 5.0.6 on 2024-06-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='dish_halves', to='health_app.category', verbose_name='Категория'),
        ),
    ]
