# Generated by Django 5.0.6 on 2024-05-31 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='dishhalf',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_halves', to='health_app.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='dishhalf',
            name='contraindications',
            field=models.ManyToManyField(blank=True, to='health_app.allergy', verbose_name='Противопоказания'),
        ),
        migrations.AddField(
            model_name='combination',
            name='half1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half1', to='health_app.dishhalf', verbose_name='Первая половина'),
        ),
        migrations.AddField(
            model_name='combination',
            name='half2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half2', to='health_app.dishhalf', verbose_name='Вторая половина'),
        ),
        migrations.AlterUniqueTogether(
            name='combination',
            unique_together={('half1', 'half2')},
        ),
    ]
