# Generated by Django 5.0.6 on 2024-06-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishhalf',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='dishhalf',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='health_app.product', verbose_name='Продукты'),
        ),
    ]
