# Generated by Django 5.0.6 on 2024-06-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combination',
            name='half2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half2', to='health_app.dishhalf', verbose_name='Вторая половина'),
        ),
    ]
