# Generated by Django 5.0.6 on 2024-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cooking_method',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
