# Generated by Django 5.0.6 on 2024-06-01 17:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
