# Generated by Django 5.0.6 on 2024-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_alter_dishhalf_image_alter_dishhalf_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishhalf',
            name='products',
            field=models.ManyToManyField(blank=True, to='health_app.product', verbose_name='Продукты'),
        ),
    ]
