# Generated by Django 5.0.6 on 2024-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_alter_dishhalf_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='allergies',
        ),
        migrations.AlterField(
            model_name='dishhalf',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='allergies',
            field=models.ManyToManyField(to='health_app.allergy', verbose_name='Список аллергенов'),
        ),
    ]
