# Generated by Django 5.0.6 on 2024-06-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_product_likes_alter_rating_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
