# Generated by Django 5.0.6 on 2024-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_remove_customer_user_remove_customer_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='dish_halves',
            field=models.ManyToManyField(blank=True, null=True, to='health_app.dishhalf'),
        ),
    ]
