# Generated by Django 5.0.6 on 2024-05-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_alter_allergy_dish_halves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='health_app.allergy', verbose_name='Список аллергенов'),
        ),
    ]
