# Generated by Django 5.0.6 on 2024-06-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_remove_product_ingredients_alter_product_is_prepared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Продукты'),
        ),
    ]
