# Generated by Django 5.0.6 on 2024-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0007_alter_dishhalf_calories_alter_dishhalf_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='dish_halves',
        ),
        migrations.AddField(
            model_name='dishhalf',
            name='contraindications',
            field=models.ManyToManyField(blank=True, null=True, to='health_app.allergy'),
        ),
    ]
