# Generated by Django 5.0.6 on 2024-05-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0009_alter_customer_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weight',
        ),
        migrations.AddField(
            model_name='dishhalf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dishhalf',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='half1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half1', to='health_app.dishhalf', verbose_name='Первая половина'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='half2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half2', to='health_app.dishhalf', verbose_name='Вторая половина'),
        ),
        migrations.AlterField(
            model_name='dishhalf',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_halves', to='health_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dishhalf',
            name='contraindications',
            field=models.ManyToManyField(blank=True, to='health_app.allergy', verbose_name='Противопоказания'),
        ),
        migrations.AlterField(
            model_name='dishhalf',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
